trigger:
- main

stages:

# ---------------------- Deliver Stage ----------------------
- stage: Deliver
  displayName: 'Build and Publish Artifact'
  jobs:
    - job: BuildAndPublish
      displayName: 'Build project and publish artifact'
      pool:
        name: Final
      steps:
        - script: |
            "C:\\Users\\user\\Downloads\\apache-maven-3.9.9-bin\\apache-maven-3.9.9\\bin\\mvn.cmd" clean package
          displayName: 'Build using full Maven path'

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: 'target'
            artifactName: 'FinalProjectArtifact'
            publishLocation: 'Container'

# ---------------------- Dev Deployment ----------------------
- stage: DeployToDev
  displayName: 'Deploy to Dev Environment'
  dependsOn: Deliver
  jobs:
    - deployment: DeployToDevGroup
      displayName: 'Deploy using Dev Deployment Group'
      environment:
        name: Dev
        resourceType: DeploymentGroup
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: FinalProjectArtifact
              - script: echo "🚀 Deployed to Dev environment"
                displayName: 'Simulate deployment'

# ---------------------- QAT Deployment ----------------------
- stage: DeployToQAT
  displayName: 'Deploy to QAT Environment'
  dependsOn: DeployToDev
  jobs:
    - deployment: DeployToQATGroup
      displayName: 'Deploy using QAT Deployment Group'
      environment:
        name: QAT
        resourceType: DeploymentGroup
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: FinalProjectArtifact
              - script: echo "🧪 Deployed to QAT environment"
                displayName: 'Simulate deployment'

# ---------------------- Staging Deployment ----------------------
- stage: DeployToStaging
  displayName: 'Deploy to Staging Environment'
  dependsOn: DeployToQAT
  jobs:
    - deployment: DeployToStagingGroup
      displayName: 'Deploy using Staging Deployment Group'
      environment:
        name: Staging
        resourceType: DeploymentGroup
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: FinalProjectArtifact
              - script: echo "🛠️ Deployed to Staging environment"
                displayName: 'Simulate deployment'

# ---------------------- Production Deployment ----------------------
- stage: DeployToProduction
  displayName: 'Deploy to Production Environment'
  dependsOn: DeployToStaging
  jobs:
    - deployment: DeployToProdGroup
      displayName: 'Deploy using Production Deployment Group'
      environment:
        name: Production
        resourceType: DeploymentGroup
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: FinalProjectArtifact
              - script: echo "🚨 Deployed to Production environment"
                displayName: 'Simulate deployment'
