trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

# -----------------------------------------
- stage: Deliver
  displayName: 'Build and Deliver Artifact'
  jobs:
    - job: BuildAndPackage
      steps:
        - task: JavaToolInstaller@0
          inputs:
            versionSpec: '17'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'

        - script: mvn clean package
          displayName: 'Package with Maven'

        - script: echo " Artifact (e.g. .jar) delivered to mock location"
          displayName: 'Mock artifact delivery'

# -----------------------------------------
- stage: DeployToDev
  displayName: 'Deploy to Dev Environment'
  dependsOn: Deliver
  jobs:
    - job: DeployDev
      steps:
        - script: echo " Deploying to Dev Env... (mock)"
        - script: echo " Launching app at http://dev.example.com (mock)"

# -----------------------------------------
- stage: DeployToQAT
  displayName: 'Deploy to QAT Environment'
  dependsOn: DeployToDev
  jobs:
    - job: DeployQAT
      steps:
        - script: echo " Deploying to QAT Env... (mock)"

# -----------------------------------------
- stage: DeployToStaging
  displayName: 'Deploy to Staging Environment'
  dependsOn: DeployToQAT
  jobs:
    - job: DeployStaging
      steps:
        - script: echo " Deploying to Staging Env... (mock)"

# -----------------------------------------
- stage: DeployToProduction
  displayName: 'Deploy to Production Environment'
  dependsOn: DeployToStaging
  jobs:
    - job: DeployProd
      steps:
        - script: echo " Deploying to Production Env... (mock)"
