trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'

# Run Checkstyle
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'checkstyle:check'
    options: '-B'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'

# Run tests with coverage
- script: mvn clean verify
  displayName: 'Run tests and generate JaCoCo coverage'
