trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# Static code analysis
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'checkstyle:check'
    options: '-B'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'

# Run tests and generate JaCoCo coverage
- script: mvn clean verify
  displayName: 'Run tests and generate JaCoCo coverage'

# Publish code coverage to DevOps UI
- task: PublishCodeCoverageResults@2
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'
