trigger:
- main

pool:
  name: Final  # your CI agent pool

stages:

# ---------------------- Deliver Stage ----------------------
- stage: Deliver
  displayName: 'Build and Publish Artifact'
  jobs:
    - job: BuildAndPublish
      displayName: 'Build project and publish artifact'
      steps:
        - script: |
            "C:\\Users\\user\\Downloads\\apache-maven-3.9.9-bin\\apache-maven-3.9.9\\bin\\mvn.cmd" clean package
          displayName: 'Build with full Maven path'

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: 'target'
            artifactName: 'FinalProjectArtifact'
            publishLocation: 'Container'

# ---------------------- Mock Dev Deployment ----------------------
- stage: DeployToDev
  displayName: 'Simulate Deploy to Dev'
  dependsOn: Deliver
  jobs:
    - job: EchoDev
      steps:
        - script: echo "🚀 Simulating deployment to Dev environment"

# ---------------------- Mock QAT Deployment ----------------------
- stage: DeployToQAT
  displayName: 'Simulate Deploy to QAT'
  dependsOn: DeployToDev
  jobs:
    - job: EchoQAT
      steps:
        - script: echo "🧪 Simulating deployment to QAT environment"

# ---------------------- Mock Staging Deployment ----------------------
- stage: DeployToStaging
  displayName: 'Simulate Deploy to Staging'
  dependsOn: DeployToQAT
  jobs:
    - job: EchoStaging
      steps:
        - script: echo "🛠️ Simulating deployment to Staging environment"

# ---------------------- Mock Production Deployment ----------------------
- stage: DeployToProduction
  displayName: 'Simulate Deploy to Production'
  dependsOn: DeployToStaging
  jobs:
    - job: EchoProd
      steps:
        - script: echo "🚨 Simulating deployment to Production environment"
